version: '3'

services:
  front:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./web/src/:/app/src
      - builds:/app/src/assets/builds
    depends_on:
      - mobile
      - back

  back:
    build:
      context: server/
      dockerfile: Dockerfile
    command: npm run serve
    ports:
      - 8080:3000
    volumes:
      - ./server/src:/app/src
    environment:
      - BASE_URL=area.famille4.com

  mobile:
    build:
      context: mobile/
      dockerfile: Dockerfile
    command: 'mv /build.apk /builds/build.apk'
    volumes:
      - builds:/builds

volumes:
  builds:
    driver: local
